repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
      # - id: rst-inline-touching-normal
      - id: rst-directive-colons
      - id: text-unicode-replacement-char
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"] # solves conflicts between black and isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--select=E9,F63,F7,F82", "--show-source", "--statistics"]
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.0
    hooks:
      - id: pylint
        name: pylint
        types: [python]
        exclude: ^examples/|^tests/|^setup.py$
        args: ["--rcfile=.pylintrc", "-d", "R0801"] # ignore duplicate code
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        name: mypy
        args:
          [
            --config-file=pyproject.toml,
            --install-types,
            --non-interactive,
            rebalance,
          ]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
